// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginRequest.proto

package protobufmodels;

public final class LoginRequest {
  private LoginRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRequsetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginRequset)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>.LoginRequset.UUID instance = 3;</code>
     * @return Whether the instance field is set.
     */
    boolean hasInstance();
    /**
     * <code>.LoginRequset.UUID instance = 3;</code>
     * @return The instance.
     */
    protobufmodels.LoginRequest.LoginRequset.UUID getInstance();
    /**
     * <code>.LoginRequset.UUID instance = 3;</code>
     */
    protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder getInstanceOrBuilder();

    /**
     * <code>.LoginRequset.UserType userType = 4;</code>
     * @return The enum numeric value on the wire for userType.
     */
    int getUserTypeValue();
    /**
     * <code>.LoginRequset.UserType userType = 4;</code>
     * @return The userType.
     */
    protobufmodels.LoginRequest.LoginRequset.UserType getUserType();
  }
  /**
   * Protobuf type {@code LoginRequset}
   */
  public static final class LoginRequset extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginRequset)
      LoginRequsetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRequset.newBuilder() to construct.
    private LoginRequset(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequset() {
      password_ = "";
      userType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginRequset();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequset(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 26: {
              protobufmodels.LoginRequest.LoginRequset.UUID.Builder subBuilder = null;
              if (instance_ != null) {
                subBuilder = instance_.toBuilder();
              }
              instance_ = input.readMessage(protobufmodels.LoginRequest.LoginRequset.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(instance_);
                instance_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              userType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobufmodels.LoginRequest.internal_static_LoginRequset_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobufmodels.LoginRequest.internal_static_LoginRequset_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobufmodels.LoginRequest.LoginRequset.class, protobufmodels.LoginRequest.LoginRequset.Builder.class);
    }

    /**
     * Protobuf enum {@code LoginRequset.UserType}
     */
    public enum UserType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>USER = 0;</code>
       */
      USER(0),
      /**
       * <code>ADMIN = 1;</code>
       */
      ADMIN(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>USER = 0;</code>
       */
      public static final int USER_VALUE = 0;
      /**
       * <code>ADMIN = 1;</code>
       */
      public static final int ADMIN_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UserType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static UserType forNumber(int value) {
        switch (value) {
          case 0: return USER;
          case 1: return ADMIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
              public UserType findValueByNumber(int number) {
                return UserType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobufmodels.LoginRequest.LoginRequset.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserType[] VALUES = values();

      public static UserType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:LoginRequset.UserType)
    }

    public interface UUIDOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LoginRequset.UUID)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      java.lang.String getUuid();
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      com.google.protobuf.ByteString
          getUuidBytes();
    }
    /**
     * Protobuf type {@code LoginRequset.UUID}
     */
    public static final class UUID extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:LoginRequset.UUID)
        UUIDOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use UUID.newBuilder() to construct.
      private UUID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private UUID() {
        uuid_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new UUID();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private UUID(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                uuid_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufmodels.LoginRequest.internal_static_LoginRequset_UUID_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufmodels.LoginRequest.internal_static_LoginRequset_UUID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufmodels.LoginRequest.LoginRequset.UUID.class, protobufmodels.LoginRequest.LoginRequset.UUID.Builder.class);
      }

      public static final int UUID_FIELD_NUMBER = 1;
      private volatile java.lang.Object uuid_;
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      @java.lang.Override
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getUuidBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUuidBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protobufmodels.LoginRequest.LoginRequset.UUID)) {
          return super.equals(obj);
        }
        protobufmodels.LoginRequest.LoginRequset.UUID other = (protobufmodels.LoginRequest.LoginRequset.UUID) obj;

        if (!getUuid()
            .equals(other.getUuid())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protobufmodels.LoginRequest.LoginRequset.UUID parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protobufmodels.LoginRequest.LoginRequset.UUID prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code LoginRequset.UUID}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:LoginRequset.UUID)
          protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protobufmodels.LoginRequest.internal_static_LoginRequset_UUID_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protobufmodels.LoginRequest.internal_static_LoginRequset_UUID_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protobufmodels.LoginRequest.LoginRequset.UUID.class, protobufmodels.LoginRequest.LoginRequset.UUID.Builder.class);
        }

        // Construct using protobufmodels.LoginRequest.LoginRequset.UUID.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          uuid_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protobufmodels.LoginRequest.internal_static_LoginRequset_UUID_descriptor;
        }

        @java.lang.Override
        public protobufmodels.LoginRequest.LoginRequset.UUID getDefaultInstanceForType() {
          return protobufmodels.LoginRequest.LoginRequset.UUID.getDefaultInstance();
        }

        @java.lang.Override
        public protobufmodels.LoginRequest.LoginRequset.UUID build() {
          protobufmodels.LoginRequest.LoginRequset.UUID result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public protobufmodels.LoginRequest.LoginRequset.UUID buildPartial() {
          protobufmodels.LoginRequest.LoginRequset.UUID result = new protobufmodels.LoginRequest.LoginRequset.UUID(this);
          result.uuid_ = uuid_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protobufmodels.LoginRequest.LoginRequset.UUID) {
            return mergeFrom((protobufmodels.LoginRequest.LoginRequset.UUID)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protobufmodels.LoginRequest.LoginRequset.UUID other) {
          if (other == protobufmodels.LoginRequest.LoginRequset.UUID.getDefaultInstance()) return this;
          if (!other.getUuid().isEmpty()) {
            uuid_ = other.uuid_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protobufmodels.LoginRequest.LoginRequset.UUID parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protobufmodels.LoginRequest.LoginRequset.UUID) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object uuid_ = "";
        /**
         * <code>string uuid = 1;</code>
         * @return The uuid.
         */
        public java.lang.String getUuid() {
          java.lang.Object ref = uuid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            uuid_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string uuid = 1;</code>
         * @return The bytes for uuid.
         */
        public com.google.protobuf.ByteString
            getUuidBytes() {
          java.lang.Object ref = uuid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uuid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string uuid = 1;</code>
         * @param value The uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          uuid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string uuid = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearUuid() {
          
          uuid_ = getDefaultInstance().getUuid();
          onChanged();
          return this;
        }
        /**
         * <code>string uuid = 1;</code>
         * @param value The bytes for uuid to set.
         * @return This builder for chaining.
         */
        public Builder setUuidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          uuid_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:LoginRequset.UUID)
      }

      // @@protoc_insertion_point(class_scope:LoginRequset.UUID)
      private static final protobufmodels.LoginRequest.LoginRequset.UUID DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protobufmodels.LoginRequest.LoginRequset.UUID();
      }

      public static protobufmodels.LoginRequest.LoginRequset.UUID getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<UUID>
          PARSER = new com.google.protobuf.AbstractParser<UUID>() {
        @java.lang.Override
        public UUID parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new UUID(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<UUID> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<UUID> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public protobufmodels.LoginRequest.LoginRequset.UUID getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTANCE_FIELD_NUMBER = 3;
    private protobufmodels.LoginRequest.LoginRequset.UUID instance_;
    /**
     * <code>.LoginRequset.UUID instance = 3;</code>
     * @return Whether the instance field is set.
     */
    @java.lang.Override
    public boolean hasInstance() {
      return instance_ != null;
    }
    /**
     * <code>.LoginRequset.UUID instance = 3;</code>
     * @return The instance.
     */
    @java.lang.Override
    public protobufmodels.LoginRequest.LoginRequset.UUID getInstance() {
      return instance_ == null ? protobufmodels.LoginRequest.LoginRequset.UUID.getDefaultInstance() : instance_;
    }
    /**
     * <code>.LoginRequset.UUID instance = 3;</code>
     */
    @java.lang.Override
    public protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder getInstanceOrBuilder() {
      return getInstance();
    }

    public static final int USERTYPE_FIELD_NUMBER = 4;
    private int userType_;
    /**
     * <code>.LoginRequset.UserType userType = 4;</code>
     * @return The enum numeric value on the wire for userType.
     */
    @java.lang.Override public int getUserTypeValue() {
      return userType_;
    }
    /**
     * <code>.LoginRequset.UserType userType = 4;</code>
     * @return The userType.
     */
    @java.lang.Override public protobufmodels.LoginRequest.LoginRequset.UserType getUserType() {
      @SuppressWarnings("deprecation")
      protobufmodels.LoginRequest.LoginRequset.UserType result = protobufmodels.LoginRequest.LoginRequset.UserType.valueOf(userType_);
      return result == null ? protobufmodels.LoginRequest.LoginRequset.UserType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeUInt32(1, id_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (instance_ != null) {
        output.writeMessage(3, getInstance());
      }
      if (userType_ != protobufmodels.LoginRequest.LoginRequset.UserType.USER.getNumber()) {
        output.writeEnum(4, userType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (instance_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getInstance());
      }
      if (userType_ != protobufmodels.LoginRequest.LoginRequset.UserType.USER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, userType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobufmodels.LoginRequest.LoginRequset)) {
        return super.equals(obj);
      }
      protobufmodels.LoginRequest.LoginRequset other = (protobufmodels.LoginRequest.LoginRequset) obj;

      if (getId()
          != other.getId()) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (hasInstance() != other.hasInstance()) return false;
      if (hasInstance()) {
        if (!getInstance()
            .equals(other.getInstance())) return false;
      }
      if (userType_ != other.userType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      if (hasInstance()) {
        hash = (37 * hash) + INSTANCE_FIELD_NUMBER;
        hash = (53 * hash) + getInstance().hashCode();
      }
      hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + userType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobufmodels.LoginRequest.LoginRequset parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobufmodels.LoginRequest.LoginRequset prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginRequset}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginRequset)
        protobufmodels.LoginRequest.LoginRequsetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobufmodels.LoginRequest.internal_static_LoginRequset_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobufmodels.LoginRequest.internal_static_LoginRequset_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobufmodels.LoginRequest.LoginRequset.class, protobufmodels.LoginRequest.LoginRequset.Builder.class);
      }

      // Construct using protobufmodels.LoginRequest.LoginRequset.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        password_ = "";

        if (instanceBuilder_ == null) {
          instance_ = null;
        } else {
          instance_ = null;
          instanceBuilder_ = null;
        }
        userType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobufmodels.LoginRequest.internal_static_LoginRequset_descriptor;
      }

      @java.lang.Override
      public protobufmodels.LoginRequest.LoginRequset getDefaultInstanceForType() {
        return protobufmodels.LoginRequest.LoginRequset.getDefaultInstance();
      }

      @java.lang.Override
      public protobufmodels.LoginRequest.LoginRequset build() {
        protobufmodels.LoginRequest.LoginRequset result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobufmodels.LoginRequest.LoginRequset buildPartial() {
        protobufmodels.LoginRequest.LoginRequset result = new protobufmodels.LoginRequest.LoginRequset(this);
        result.id_ = id_;
        result.password_ = password_;
        if (instanceBuilder_ == null) {
          result.instance_ = instance_;
        } else {
          result.instance_ = instanceBuilder_.build();
        }
        result.userType_ = userType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobufmodels.LoginRequest.LoginRequset) {
          return mergeFrom((protobufmodels.LoginRequest.LoginRequset)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobufmodels.LoginRequest.LoginRequset other) {
        if (other == protobufmodels.LoginRequest.LoginRequset.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.hasInstance()) {
          mergeInstance(other.getInstance());
        }
        if (other.userType_ != 0) {
          setUserTypeValue(other.getUserTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobufmodels.LoginRequest.LoginRequset parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobufmodels.LoginRequest.LoginRequset) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>uint32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private protobufmodels.LoginRequest.LoginRequset.UUID instance_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protobufmodels.LoginRequest.LoginRequset.UUID, protobufmodels.LoginRequest.LoginRequset.UUID.Builder, protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder> instanceBuilder_;
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       * @return Whether the instance field is set.
       */
      public boolean hasInstance() {
        return instanceBuilder_ != null || instance_ != null;
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       * @return The instance.
       */
      public protobufmodels.LoginRequest.LoginRequset.UUID getInstance() {
        if (instanceBuilder_ == null) {
          return instance_ == null ? protobufmodels.LoginRequest.LoginRequset.UUID.getDefaultInstance() : instance_;
        } else {
          return instanceBuilder_.getMessage();
        }
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      public Builder setInstance(protobufmodels.LoginRequest.LoginRequset.UUID value) {
        if (instanceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          instance_ = value;
          onChanged();
        } else {
          instanceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      public Builder setInstance(
          protobufmodels.LoginRequest.LoginRequset.UUID.Builder builderForValue) {
        if (instanceBuilder_ == null) {
          instance_ = builderForValue.build();
          onChanged();
        } else {
          instanceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      public Builder mergeInstance(protobufmodels.LoginRequest.LoginRequset.UUID value) {
        if (instanceBuilder_ == null) {
          if (instance_ != null) {
            instance_ =
              protobufmodels.LoginRequest.LoginRequset.UUID.newBuilder(instance_).mergeFrom(value).buildPartial();
          } else {
            instance_ = value;
          }
          onChanged();
        } else {
          instanceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      public Builder clearInstance() {
        if (instanceBuilder_ == null) {
          instance_ = null;
          onChanged();
        } else {
          instance_ = null;
          instanceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      public protobufmodels.LoginRequest.LoginRequset.UUID.Builder getInstanceBuilder() {
        
        onChanged();
        return getInstanceFieldBuilder().getBuilder();
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      public protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder getInstanceOrBuilder() {
        if (instanceBuilder_ != null) {
          return instanceBuilder_.getMessageOrBuilder();
        } else {
          return instance_ == null ?
              protobufmodels.LoginRequest.LoginRequset.UUID.getDefaultInstance() : instance_;
        }
      }
      /**
       * <code>.LoginRequset.UUID instance = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobufmodels.LoginRequest.LoginRequset.UUID, protobufmodels.LoginRequest.LoginRequset.UUID.Builder, protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder> 
          getInstanceFieldBuilder() {
        if (instanceBuilder_ == null) {
          instanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobufmodels.LoginRequest.LoginRequset.UUID, protobufmodels.LoginRequest.LoginRequset.UUID.Builder, protobufmodels.LoginRequest.LoginRequset.UUIDOrBuilder>(
                  getInstance(),
                  getParentForChildren(),
                  isClean());
          instance_ = null;
        }
        return instanceBuilder_;
      }

      private int userType_ = 0;
      /**
       * <code>.LoginRequset.UserType userType = 4;</code>
       * @return The enum numeric value on the wire for userType.
       */
      @java.lang.Override public int getUserTypeValue() {
        return userType_;
      }
      /**
       * <code>.LoginRequset.UserType userType = 4;</code>
       * @param value The enum numeric value on the wire for userType to set.
       * @return This builder for chaining.
       */
      public Builder setUserTypeValue(int value) {
        
        userType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.LoginRequset.UserType userType = 4;</code>
       * @return The userType.
       */
      @java.lang.Override
      public protobufmodels.LoginRequest.LoginRequset.UserType getUserType() {
        @SuppressWarnings("deprecation")
        protobufmodels.LoginRequest.LoginRequset.UserType result = protobufmodels.LoginRequest.LoginRequset.UserType.valueOf(userType_);
        return result == null ? protobufmodels.LoginRequest.LoginRequset.UserType.UNRECOGNIZED : result;
      }
      /**
       * <code>.LoginRequset.UserType userType = 4;</code>
       * @param value The userType to set.
       * @return This builder for chaining.
       */
      public Builder setUserType(protobufmodels.LoginRequest.LoginRequset.UserType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        userType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.LoginRequset.UserType userType = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserType() {
        
        userType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginRequset)
    }

    // @@protoc_insertion_point(class_scope:LoginRequset)
    private static final protobufmodels.LoginRequest.LoginRequset DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobufmodels.LoginRequest.LoginRequset();
    }

    public static protobufmodels.LoginRequest.LoginRequset getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequset>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequset>() {
      @java.lang.Override
      public LoginRequset parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequset(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequset> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequset> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobufmodels.LoginRequest.LoginRequset getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequset_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequset_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequset_UUID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequset_UUID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022LoginRequest.proto\"\263\001\n\014LoginRequset\022\n\n" +
      "\002id\030\001 \001(\r\022\020\n\010password\030\002 \001(\t\022$\n\010instance\030" +
      "\003 \001(\0132\022.LoginRequset.UUID\022(\n\010userType\030\004 " +
      "\001(\0162\026.LoginRequset.UserType\032\024\n\004UUID\022\014\n\004u" +
      "uid\030\001 \001(\t\"\037\n\010UserType\022\010\n\004USER\020\000\022\t\n\005ADMIN" +
      "\020\001B\036\n\016protobufmodelsB\014LoginRequestb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LoginRequset_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequset_descriptor,
        new java.lang.String[] { "Id", "Password", "Instance", "UserType", });
    internal_static_LoginRequset_UUID_descriptor =
      internal_static_LoginRequset_descriptor.getNestedTypes().get(0);
    internal_static_LoginRequset_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequset_UUID_descriptor,
        new java.lang.String[] { "Uuid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
